# Back Propagation using Pytorch

In [9]:
# Lets import torch
import torch

In [10]:
# Version check
torch.__version__

'1.5.1+cpu'

In [11]:
# Lets create a tensor of 4 with gradient as True
x = torch.tensor(4.0, requires_grad = True)

In [12]:
# Lets see our x
x

tensor(4., requires_grad=True)

In [13]:
# Lets define an equation y=x^2
y = x**2
# Lets see y
y

tensor(16., grad_fn=<PowBackward0>)

In [14]:
# Lets perform back propagation
y.backward()

In [15]:
# Lets see the result
x.grad

tensor(8.)

In [16]:
# Lets perform some complex functions
list = [[2.,3.,1.], [4.,5.,3.], [7.,6.,4.]]
torch_input = torch.tensor(list, requires_grad = True)

In [17]:
# Lets see
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [19]:
# y=x**3+x**2
y = torch_input**3 + torch_input**2

In [20]:
# Lets see y
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [21]:
# Lets sum the above matrix
z = y.sum()

In [22]:
# lets see z
z

tensor(1040., grad_fn=<SumBackward0>)

In [24]:
# Back propagation
z.backward()

In [26]:
# Lets see the result
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])