### Getting started with Pytorch
Tensors Basics

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [1]:
# Lets import torch
import torch

In [2]:
# Lets check the version before using
torch.__version__

'1.5.1+cpu'

In [3]:
# Lets import numpy
import numpy as np

In [5]:
# List
list = [3,4,5,6]

In [6]:
# Converting list into array
arr = np.array(list)

In [7]:
# Lets see the shape of the array
arr.dtype

dtype('int32')

### Converting Numpy arrays into Pytorch tensors

In [8]:
# Converting the Numpy array to tensor
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [9]:
# Indexing
tensors[0:2]

tensor([3, 4], dtype=torch.int32)

In [10]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [11]:
# Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3] = 100

In [15]:
# Lets check the array 
arr

array([  3,   4,   5, 100])

We can see the change also happened in the numpy array as well as both are using the same memory location.

In [16]:
# In order to prevent the above set of actions we use
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [19]:
# Lets again replace some elements from the tensor and see whether it impacts the numpy array or not
tensor_arr[3] = 120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120], dtype=torch.int32)
[  3   4   5 100]


We can see from the above output that the change happened only with the tensor.

In [20]:
# Zeros and ones
torch.zeros(2,3,dtype = torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [21]:
torch.ones(2,3,dtype = torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [31]:
# Creating a 2D array
a = torch.tensor(np.arange(0,15).reshape(5,3))
print(a)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)


In [30]:
# Indexing
a[0:1]

tensor([[0, 1, 2]], dtype=torch.int32)

### Arithmatic Operations

In [32]:
# Addition
a = torch.tensor([3,4,5], dtype = torch.float)
b = torch.tensor([4,5,6], dtype = torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [33]:
# Sum function
torch.add(a,b).sum()

tensor(27.)

In [34]:
# Lets create a varible to store values
c = torch.zeros(3)

In [35]:
# Lets check the initial c values
c

tensor([0., 0., 0.])

In [36]:
# Lets store the values
torch.add(a,b,out = c)

tensor([ 7.,  9., 11.])

In [37]:
# Lets see c 
c

tensor([ 7.,  9., 11.])

In [38]:
# Multiplication
x = torch.tensor([3,4,5],dtype = torch.float)
y = torch.tensor([4,5,6],dtype = torch.float)
x.mul(y)

tensor([12., 20., 30.])

In [39]:
# Dot product
x.dot(y)

tensor(62.)

In [41]:
# Matrix multiplication
x = torch.tensor([[1,4,2], [1,5,5]], dtype = torch.float)
y = torch.tensor([[5,7], [8,6], [9,11]],dtype = torch.float)
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [43]:
# We can also use mm
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [44]:
# x@y can also be used
x@y

tensor([[55., 53.],
        [90., 92.]])